using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using Newtonsoft.Json.Linq;

namespace Bcf.Vocabulary.Generator
{
    /// <summary>
    /// Turns bcf-extensions.json into C# constants. The same file is compiled
    /// into the generator utility and into the tests: the test generates the
    /// code afresh and compares it with what was committed, so a drift between
    /// the vocabulary and the code is caught at build time and not at run time
    /// on a user's machine.
    ///
    /// Превращает bcf-extensions.json в константы C#. Один и тот же файл
    /// компилируется и в утилиту-генератор, и в тесты: тест генерирует код
    /// заново и сверяет с закоммиченным, поэтому расхождение справочника и кода
    /// ловится на сборке, а не в рантайме у пользователя.
    /// </summary>
    public static class VocabularyCodeGenerator
    {
        public static string Generate(string vocabularyJson)
        {
            if (vocabularyJson == null) throw new ArgumentNullException(nameof(vocabularyJson));

            JObject root = JObject.Parse(vocabularyJson);
            var sb = new StringBuilder();

            sb.Append(Header(Text(root, "vocabularyVersion")));

            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine();
            sb.AppendLine("namespace Bcf.Core.Vocabulary");
            sb.AppendLine("{");
            sb.AppendLine("    public static partial class BcfVocabulary");
            sb.AppendLine("    {");
            AppendDoc(sb, "        ",
                "The vocabulary version (semver). A service reports its own — a difference in the major part is reason to warn the user.",
                "Версия справочника (semver). Сервис отдаёт свою — расхождение мажорной части повод предупредить пользователя.");
            sb.AppendLine("        public const string VocabularyVersion = " + Literal(Text(root, "vocabularyVersion")) + ";");
            sb.AppendLine();
            AppendDoc(sb, "        ",
                "The primary target BCF version.",
                "Основная целевая версия BCF.");
            sb.AppendLine("        public const string TargetBcfVersion = " + Literal(Text(root, "bcfTargetVersion")) + ";");
            sb.AppendLine();
            AppendDoc(sb, "        ",
                "The switchable BCF version for third-party receiving tools.",
                "Переключаемая версия BCF для сторонних приёмников.");
            sb.AppendLine("        public const string FallbackBcfVersion = " + Literal(Text(root, "bcfFallbackVersion")) + ";");
            sb.AppendLine();

            AppendSimpleGroup(sb, root, "topicTypes", "TopicTypes",
                "The topic type (TopicType).",
                "Тип замечания (TopicType).");
            AppendStatusGroup(sb, root);
            AppendSimpleGroup(sb, root, "priorities", "Priorities",
                "The topic priority (Priority).",
                "Приоритет замечания (Priority).");
            AppendLabelGroup(sb, root);
            AppendSimpleGroup(sb, root, "stages", "Stages",
                "The project stage (Stage).",
                "Стадия проекта (Stage).");
            AppendMapping(sb, root, "navisworksStatusMapping", "NavisworksStatusToBcf",
                "A Clash Detective status to a BCF TopicStatus. Defaults; the user overrides them in the export settings.",
                "Статус Clash Detective → TopicStatus BCF. Умолчания; пользователь переопределяет их в настройках выгрузки.",
                bcfSide: MappingSide.Value);
            AppendMapping(sb, root, "bcfStatusToNavisworksMapping", "BcfStatusToNavisworks",
                "A BCF TopicStatus to a Clash Detective status. The mapping is not one to one: the Navisworks set of statuses is the poorer one.",
                "TopicStatus BCF → статус Clash Detective. Отображение не биективно: набор статусов Navisworks беднее.",
                bcfSide: MappingSide.Key);

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static string Header(string vocabularyVersion)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//     Generated from " + RepositoryPaths.VocabularyRelativePath + " (vocabularyVersion " + vocabularyVersion + ").");
            sb.AppendLine("//");
            sb.AppendLine("//     Do not edit by hand. To update: dotnet run --project Bcf.Vocabulary.Generator");
            sb.AppendLine("//     A drift between this file and the vocabulary fails the VocabularyDriftTests test,");
            sb.AppendLine("//     that is, it is caught at build time and not at run time on a user's machine.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            return sb.ToString();
        }

        private static void AppendSimpleGroup(
            StringBuilder sb, JObject root, string jsonKey, string className, string summaryEn, string summaryRu)
        {
            List<JObject> items = Items(root, jsonKey);

            AppendDoc(sb, "        ", summaryEn, summaryRu);
            sb.AppendLine("        public static class " + className);
            sb.AppendLine("        {");
            AppendValueConstants(sb, items);
            AppendDefault(sb, items);
            AppendAll(sb, items);
            AppendRussianLabels(sb, items);
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        private static void AppendStatusGroup(StringBuilder sb, JObject root)
        {
            List<JObject> items = Items(root, "topicStatuses");

            AppendDoc(sb, "        ",
                "The topic status (TopicStatus) and its lifecycle.",
                "Статус замечания (TopicStatus) и его жизненный цикл.");
            sb.AppendLine("        public static class TopicStatuses");
            sb.AppendLine("        {");
            AppendValueConstants(sb, items);
            AppendDefault(sb, items);
            AppendAll(sb, items);
            AppendRussianLabels(sb, items);

            sb.AppendLine();
            AppendDoc(sb, "            ",
                "The terminal statuses: the only way out of them is Reopened.",
                "Конечные статусы: из них выходит только Reopened.");
            sb.AppendLine("            public static readonly IReadOnlyList<string> Terminal = new[]");
            sb.AppendLine("            {");
            foreach (JObject item in items.Where(i => Flag(i, "isTerminal")))
            {
                sb.AppendLine("                " + Identifier(Text(item, "value")) + ",");
            }
            sb.AppendLine("            };");

            AppendFlagList(sb, items, "requiresComment", "RequiresComment",
                "The statuses that must not be set without a comment: closing without a reason devalues the whole system.",
                "Статусы, которые нельзя ставить без комментария: закрытие без обоснования обесценивает всю систему.");
            AppendFlagList(sb, items, "requiresAssignee", "RequiresAssignee",
                "The statuses that need an assignee filled in.",
                "Статусы, требующие заполненного исполнителя.");

            sb.AppendLine();
            AppendDoc(sb, "            ",
                "The allowed transitions. The authoritative check is on the server: third-party clients know nothing of these rules.",
                "Разрешённые переходы. Авторитетная проверка — на сервере: сторонние клиенты об этих правилах не знают.");
            sb.AppendLine("            public static readonly IReadOnlyDictionary<string, IReadOnlyList<string>> AllowedTransitions =");
            sb.AppendLine("                new Dictionary<string, IReadOnlyList<string>>");
            sb.AppendLine("            {");
            foreach (JObject item in items)
            {
                var transitions = item["allowedTransitions"] as JArray;
                string values = transitions == null
                    ? string.Empty
                    : string.Join(", ", transitions.Select(t => Identifier((string)t)));
                sb.AppendLine("                { " + Identifier(Text(item, "value")) + ", new[] { " + values + " } },");
            }
            sb.AppendLine("            };");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        private static void AppendLabelGroup(StringBuilder sb, JObject root)
        {
            List<JObject> items = Items(root, "topicLabels");

            AppendDoc(sb, "        ",
                "The topic labels (TopicLabel): discipline, nature, source.",
                "Метки замечания (TopicLabel): дисциплина, характер, источник.");
            sb.AppendLine("        public static class TopicLabels");
            sb.AppendLine("        {");
            AppendValueConstants(sb, items);
            AppendAll(sb, items);
            AppendRussianLabels(sb, items);

            sb.AppendLine();
            AppendDoc(sb, "            ",
                "The group of a label: discipline / nature / source. It keeps an interface from mixing the sections of a project with the nature of a clash.",
                "Группа метки: discipline / nature / source. Нужна, чтобы в интерфейсе не мешать разделы проекта с характером коллизии.");
            sb.AppendLine("            public static readonly IReadOnlyDictionary<string, string> Groups = new Dictionary<string, string>");
            sb.AppendLine("            {");
            foreach (JObject item in items)
            {
                sb.AppendLine("                { " + Identifier(Text(item, "value")) + ", " + Literal(Text(item, "group")) + " },");
            }
            sb.AppendLine("            };");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        private static void AppendValueConstants(StringBuilder sb, List<JObject> items)
        {
            var seen = new Dictionary<string, string>(StringComparer.Ordinal);
            foreach (JObject item in items)
            {
                string value = Text(item, "value");
                string identifier = Identifier(value);

                if (seen.TryGetValue(identifier, out string previous))
                {
                    throw new InvalidOperationException(
                        "The values '" + previous + "' and '" + value + "' give one constant name '" + identifier +
                        "'. Rename one of them in the vocabulary or refine the Identifier() rule.");
                }
                seen.Add(identifier, value);

                string ru = Label(item, "ru");
                string en = Label(item, "en");

                if (!string.IsNullOrEmpty(en) || !string.IsNullOrEmpty(ru))
                {
                    AppendDoc(sb, "            ", Escape(en ?? value), Escape(ru ?? value));
                }
                sb.AppendLine("            public const string " + identifier + " = " + Literal(value) + ";");
            }
        }

        private static void AppendDefault(StringBuilder sb, List<JObject> items)
        {
            JObject defaultItem = items.FirstOrDefault(i => Flag(i, "isDefault"));
            if (defaultItem == null) return;

            sb.AppendLine();
            AppendDoc(sb, "            ",
                "The value used by default when exporting.",
                "Значение по умолчанию при выгрузке.");
            sb.AppendLine("            public const string Default = " + Identifier(Text(defaultItem, "value")) + ";");
        }

        private static void AppendAll(StringBuilder sb, List<JObject> items)
        {
            sb.AppendLine();
            AppendDoc(sb, "            ",
                "Every value, in the order of the vocabulary.",
                "Все значения в порядке справочника.");
            sb.AppendLine("            public static readonly IReadOnlyList<string> All = new[]");
            sb.AppendLine("            {");
            foreach (JObject item in items)
            {
                sb.AppendLine("                " + Identifier(Text(item, "value")) + ",");
            }
            sb.AppendLine("            };");

            List<JObject> deprecated = items.Where(i => Flag(i, "deprecated")).ToList();
            sb.AppendLine();
            AppendDoc(sb, "            ",
                "The values offered for choosing in an interface: without the ones marked deprecated. Old data carrying them is still displayed.",
                "Значения, доступные для выбора в интерфейсе: без помеченных deprecated. Старые данные с ними продолжают отображаться.");
            if (deprecated.Count == 0)
            {
                sb.AppendLine("            public static readonly IReadOnlyList<string> Selectable = All;");
            }
            else
            {
                sb.AppendLine("            public static readonly IReadOnlyList<string> Selectable = new[]");
                sb.AppendLine("            {");
                foreach (JObject item in items.Where(i => !Flag(i, "deprecated")))
                {
                    sb.AppendLine("                " + Identifier(Text(item, "value")) + ",");
                }
                sb.AppendLine("            };");
            }
        }

        private static void AppendRussianLabels(StringBuilder sb, List<JObject> items)
        {
            sb.AppendLine();
            AppendDoc(sb, "            ",
                "The Russian display labels for an interface. They never reach a file or an HTTP body.",
                "Русские подписи для интерфейса. В файлы и в тела HTTP не попадают никогда.");
            sb.AppendLine("            public static readonly IReadOnlyDictionary<string, string> LabelsRu = new Dictionary<string, string>");
            sb.AppendLine("            {");
            foreach (JObject item in items)
            {
                sb.AppendLine("                { " + Identifier(Text(item, "value")) + ", " + Literal(Label(item, "ru")) + " },");
            }
            sb.AppendLine("            };");
        }

        private static void AppendFlagList(
            StringBuilder sb, List<JObject> items, string jsonFlag, string name, string summaryEn, string summaryRu)
        {
            sb.AppendLine();
            AppendDoc(sb, "            ", summaryEn, summaryRu);
            sb.AppendLine("            public static readonly IReadOnlyList<string> " + name + " = new[]");
            sb.AppendLine("            {");
            foreach (JObject item in items.Where(i => Flag(i, jsonFlag)))
            {
                sb.AppendLine("                " + Identifier(Text(item, "value")) + ",");
            }
            sb.AppendLine("            };");
        }

        /// <summary>
        /// Writes a bilingual documentation block into the generated file:
        /// English first, Russian second — the same convention the hand-written
        /// code of this repository holds to.
        ///
        /// Пишет в генерируемый файл двуязычный блок документации: сначала
        /// английский, затем русский — по тому же соглашению, что и рукописный
        /// код этого репозитория.
        /// </summary>
        private static void AppendDoc(StringBuilder sb, string indent, string english, string russian)
        {
            sb.AppendLine(indent + "/// <summary>");
            sb.AppendLine(indent + "/// " + english);
            sb.AppendLine(indent + "/// " + russian);
            sb.AppendLine(indent + "/// </summary>");
        }

        /// <summary>
        /// Which side of a mapping table is the BCF vocabulary value and which
        /// is the Navisworks status.
        ///
        /// Какая сторона таблицы отображения — значение справочника BCF,
        /// а какая — статус Navisworks.
        /// </summary>
        private enum MappingSide
        {
            Key,
            Value
        }

        private static void AppendMapping(
            StringBuilder sb, JObject root, string jsonKey, string name, string summaryEn, string summaryRu, MappingSide bcfSide)
        {
            var map = (JObject)root[jsonKey];

            AppendDoc(sb, "        ", summaryEn, summaryRu);
            sb.AppendLine("        public static readonly IReadOnlyDictionary<string, string> " + name + " = new Dictionary<string, string>");
            sb.AppendLine("        {");
            foreach (JProperty property in map.Properties())
            {
                // Keys such as $comment are documentation inside the JSON and do
                // not reach the code
                if (property.Name.StartsWith("$", StringComparison.Ordinal)) continue;

                // The BCF side is written as a constant, the Navisworks side as a
                // string: those are ClashResultStatus values, and they have
                // nothing to do with the vocabulary.
                string key = bcfSide == MappingSide.Key
                    ? "TopicStatuses." + Identifier(property.Name)
                    : Literal(property.Name);
                string value = bcfSide == MappingSide.Value
                    ? "TopicStatuses." + Identifier((string)property.Value)
                    : Literal((string)property.Value);

                sb.AppendLine("            { " + key + ", " + value + " },");
            }
            sb.AppendLine("        };");
            sb.AppendLine();
        }

        private static List<JObject> Items(JObject root, string key)
        {
            var array = root[key] as JArray;
            if (array == null)
            {
                throw new InvalidOperationException("The vocabulary has no '" + key + "' section.");
            }
            return array.OfType<JObject>().ToList();
        }

        private static string Text(JObject item, string key)
        {
            var token = item[key];
            return token == null ? null : (string)token;
        }

        private static bool Flag(JObject item, string key)
        {
            var token = item[key];
            return token != null && (bool)token;
        }

        /// <summary>
        /// A display label of a value in the language asked for.
        /// Подпись значения на запрошенном языке.
        /// </summary>
        private static string Label(JObject item, string language)
        {
            var labels = item["labels"] as JObject;
            if (labels == null) return null;
            return (string)labels[language];
        }

        /// <summary>
        /// A constant name out of a wire value: everything but letters and
        /// digits is dropped and every word is capitalised. The case inside a
        /// word is kept, or the labels SITE (the site-plan section) and Site
        /// (found on site) would collapse into one.
        ///
        /// Имя константы из wire-значения: убираем всё, кроме букв и цифр,
        /// каждое слово с заглавной. Регистр внутри слова сохраняем, иначе метки
        /// SITE (раздел ГП) и Site (выявлено на площадке) схлопнутся в одну.
        /// </summary>
        public static string Identifier(string value)
        {
            if (string.IsNullOrEmpty(value))
            {
                throw new ArgumentException("An empty vocabulary value cannot become a constant name.", nameof(value));
            }

            var sb = new StringBuilder();
            bool startOfWord = true;

            foreach (char c in value)
            {
                if (!char.IsLetterOrDigit(c))
                {
                    startOfWord = true;
                    continue;
                }

                sb.Append(startOfWord ? char.ToUpper(c, CultureInfo.InvariantCulture) : c);
                startOfWord = false;
            }

            if (sb.Length == 0 || char.IsDigit(sb[0]))
            {
                throw new InvalidOperationException("The value '" + value + "' does not give a valid C# constant name.");
            }

            return sb.ToString();
        }

        private static string Literal(string value)
        {
            if (value == null) return "null";
            return "\"" + value.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
        }

        private static string Escape(string value)
        {
            return value == null ? null : value.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");
        }
    }
}
