using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using Newtonsoft.Json.Linq;

namespace Bcf.Vocabulary.Generator
{
    /// <summary>
    /// Превращает bcf-extensions.json в C#-константы. Один и тот же файл
    /// компилируется в утилиту-генератор и в тесты: тест генерирует код заново
    /// и сверяет с закоммиченным, поэтому расхождение справочника и кода
    /// ловится на сборке, а не в рантайме у пользователя.
    /// </summary>
    public static class VocabularyCodeGenerator
    {
        /// <summary>Относительный путь к генерируемому файлу от корня репозитория.</summary>
        public const string OutputRelativePath = "Bcf.Core/Vocabulary/BcfVocabulary.g.cs";

        /// <summary>Относительный путь к справочнику от корня репозитория.</summary>
        public const string VocabularyRelativePath = "bcf-vocabularies/bcf-extensions.json";

        public static string Generate(string vocabularyJson)
        {
            if (vocabularyJson == null) throw new ArgumentNullException(nameof(vocabularyJson));

            JObject root = JObject.Parse(vocabularyJson);
            var sb = new StringBuilder();

            sb.Append(Header(Text(root, "vocabularyVersion")));

            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine();
            sb.AppendLine("namespace Bcf.Core.Vocabulary");
            sb.AppendLine("{");
            sb.AppendLine("    public static partial class BcfVocabulary");
            sb.AppendLine("    {");
            sb.AppendLine("        /// <summary>Версия справочника (semver). Сервис отдаёт свою — расхождение мажорной части повод предупредить пользователя.</summary>");
            sb.AppendLine("        public const string VocabularyVersion = " + Literal(Text(root, "vocabularyVersion")) + ";");
            sb.AppendLine();
            sb.AppendLine("        /// <summary>Основная целевая версия BCF.</summary>");
            sb.AppendLine("        public const string TargetBcfVersion = " + Literal(Text(root, "bcfTargetVersion")) + ";");
            sb.AppendLine();
            sb.AppendLine("        /// <summary>Переключаемая версия BCF для сторонних приёмников.</summary>");
            sb.AppendLine("        public const string FallbackBcfVersion = " + Literal(Text(root, "bcfFallbackVersion")) + ";");
            sb.AppendLine();

            AppendSimpleGroup(sb, root, "topicTypes", "TopicTypes", "Тип замечания (TopicType).");
            AppendStatusGroup(sb, root);
            AppendSimpleGroup(sb, root, "priorities", "Priorities", "Приоритет замечания (Priority).");
            AppendLabelGroup(sb, root);
            AppendSimpleGroup(sb, root, "stages", "Stages", "Стадия проекта (Stage).");
            AppendMapping(sb, root, "navisworksStatusMapping", "NavisworksStatusToBcf",
                "Статус Clash Detective -> TopicStatus BCF. Дефолты; пользователь переопределяет в диалоге экспорта.",
                bcfSide: MappingSide.Value);
            AppendMapping(sb, root, "bcfStatusToNavisworksMapping", "BcfStatusToNavisworks",
                "TopicStatus BCF -> статус Clash Detective. Отображение не биективно: набор статусов Navisworks беднее.",
                bcfSide: MappingSide.Key);

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static string Header(string vocabularyVersion)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//     Сгенерировано из " + VocabularyRelativePath + " (vocabularyVersion " + vocabularyVersion + ").");
            sb.AppendLine("//");
            sb.AppendLine("//     Руками не править. Обновление: dotnet run --project Bcf.Vocabulary.Generator");
            sb.AppendLine("//     Расхождение этого файла со справочником роняет тест VocabularyDriftTests,");
            sb.AppendLine("//     то есть ловится на сборке, а не в рантайме у пользователя.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            return sb.ToString();
        }

        private static void AppendSimpleGroup(StringBuilder sb, JObject root, string jsonKey, string className, string summary)
        {
            List<JObject> items = Items(root, jsonKey);

            sb.AppendLine("        /// <summary>" + summary + "</summary>");
            sb.AppendLine("        public static class " + className);
            sb.AppendLine("        {");
            AppendValueConstants(sb, items);
            AppendDefault(sb, items);
            AppendAll(sb, items);
            AppendRussianLabels(sb, items);
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        private static void AppendStatusGroup(StringBuilder sb, JObject root)
        {
            List<JObject> items = Items(root, "topicStatuses");

            sb.AppendLine("        /// <summary>Статус замечания (TopicStatus) и его жизненный цикл.</summary>");
            sb.AppendLine("        public static class TopicStatuses");
            sb.AppendLine("        {");
            AppendValueConstants(sb, items);
            AppendDefault(sb, items);
            AppendAll(sb, items);
            AppendRussianLabels(sb, items);

            sb.AppendLine();
            sb.AppendLine("            /// <summary>Конечные статусы: из них выходит только Reopened.</summary>");
            sb.AppendLine("            public static readonly IReadOnlyList<string> Terminal = new[]");
            sb.AppendLine("            {");
            foreach (JObject item in items.Where(i => Flag(i, "isTerminal")))
            {
                sb.AppendLine("                " + Identifier(Text(item, "value")) + ",");
            }
            sb.AppendLine("            };");

            AppendFlagList(sb, items, "requiresComment", "RequiresComment",
                "Статусы, которые нельзя ставить без комментария: закрытие без обоснования обесценивает систему.");
            AppendFlagList(sb, items, "requiresAssignee", "RequiresAssignee",
                "Статусы, требующие заполненного исполнителя.");

            sb.AppendLine();
            sb.AppendLine("            /// <summary>Разрешённые переходы. Авторитетная проверка — на сервере: сторонние клиенты об этих правилах не знают.</summary>");
            sb.AppendLine("            public static readonly IReadOnlyDictionary<string, IReadOnlyList<string>> AllowedTransitions =");
            sb.AppendLine("                new Dictionary<string, IReadOnlyList<string>>");
            sb.AppendLine("            {");
            foreach (JObject item in items)
            {
                var transitions = item["allowedTransitions"] as JArray;
                string values = transitions == null
                    ? string.Empty
                    : string.Join(", ", transitions.Select(t => Identifier((string)t)));
                sb.AppendLine("                { " + Identifier(Text(item, "value")) + ", new[] { " + values + " } },");
            }
            sb.AppendLine("            };");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        private static void AppendLabelGroup(StringBuilder sb, JObject root)
        {
            List<JObject> items = Items(root, "topicLabels");

            sb.AppendLine("        /// <summary>Метки замечания (TopicLabel): дисциплина, характер, источник.</summary>");
            sb.AppendLine("        public static class TopicLabels");
            sb.AppendLine("        {");
            AppendValueConstants(sb, items);
            AppendAll(sb, items);
            AppendRussianLabels(sb, items);

            sb.AppendLine();
            sb.AppendLine("            /// <summary>Группа метки: discipline / nature / source. Нужна, чтобы в UI не мешать разделы проекта с характером коллизии.</summary>");
            sb.AppendLine("            public static readonly IReadOnlyDictionary<string, string> Groups = new Dictionary<string, string>");
            sb.AppendLine("            {");
            foreach (JObject item in items)
            {
                sb.AppendLine("                { " + Identifier(Text(item, "value")) + ", " + Literal(Text(item, "group")) + " },");
            }
            sb.AppendLine("            };");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        private static void AppendValueConstants(StringBuilder sb, List<JObject> items)
        {
            var seen = new Dictionary<string, string>(StringComparer.Ordinal);
            foreach (JObject item in items)
            {
                string value = Text(item, "value");
                string identifier = Identifier(value);

                if (seen.TryGetValue(identifier, out string previous))
                {
                    throw new InvalidOperationException(
                        "Значения '" + previous + "' и '" + value + "' дают одно имя константы '" + identifier +
                        "'. Переименуйте одно из них в справочнике либо доработайте правило Identifier().");
                }
                seen.Add(identifier, value);

                string ru = LabelRu(item);
                if (!string.IsNullOrEmpty(ru))
                {
                    sb.AppendLine("            /// <summary>" + Escape(ru) + "</summary>");
                }
                sb.AppendLine("            public const string " + identifier + " = " + Literal(value) + ";");
            }
        }

        private static void AppendDefault(StringBuilder sb, List<JObject> items)
        {
            JObject defaultItem = items.FirstOrDefault(i => Flag(i, "isDefault"));
            if (defaultItem == null) return;

            sb.AppendLine();
            sb.AppendLine("            /// <summary>Значение по умолчанию при выгрузке.</summary>");
            sb.AppendLine("            public const string Default = " + Identifier(Text(defaultItem, "value")) + ";");
        }

        private static void AppendAll(StringBuilder sb, List<JObject> items)
        {
            sb.AppendLine();
            sb.AppendLine("            /// <summary>Все значения в порядке справочника.</summary>");
            sb.AppendLine("            public static readonly IReadOnlyList<string> All = new[]");
            sb.AppendLine("            {");
            foreach (JObject item in items)
            {
                sb.AppendLine("                " + Identifier(Text(item, "value")) + ",");
            }
            sb.AppendLine("            };");

            List<JObject> deprecated = items.Where(i => Flag(i, "deprecated")).ToList();
            sb.AppendLine();
            sb.AppendLine("            /// <summary>Значения, доступные для выбора в UI: без помеченных deprecated. Старые данные с ними продолжают отображаться.</summary>");
            if (deprecated.Count == 0)
            {
                sb.AppendLine("            public static readonly IReadOnlyList<string> Selectable = All;");
            }
            else
            {
                sb.AppendLine("            public static readonly IReadOnlyList<string> Selectable = new[]");
                sb.AppendLine("            {");
                foreach (JObject item in items.Where(i => !Flag(i, "deprecated")))
                {
                    sb.AppendLine("                " + Identifier(Text(item, "value")) + ",");
                }
                sb.AppendLine("            };");
            }
        }

        private static void AppendRussianLabels(StringBuilder sb, List<JObject> items)
        {
            sb.AppendLine();
            sb.AppendLine("            /// <summary>Русские подписи для UI. В файлы и в HTTP-тела не попадают никогда.</summary>");
            sb.AppendLine("            public static readonly IReadOnlyDictionary<string, string> LabelsRu = new Dictionary<string, string>");
            sb.AppendLine("            {");
            foreach (JObject item in items)
            {
                sb.AppendLine("                { " + Identifier(Text(item, "value")) + ", " + Literal(LabelRu(item)) + " },");
            }
            sb.AppendLine("            };");
        }

        private static void AppendFlagList(StringBuilder sb, List<JObject> items, string jsonFlag, string name, string summary)
        {
            sb.AppendLine();
            sb.AppendLine("            /// <summary>" + summary + "</summary>");
            sb.AppendLine("            public static readonly IReadOnlyList<string> " + name + " = new[]");
            sb.AppendLine("            {");
            foreach (JObject item in items.Where(i => Flag(i, jsonFlag)))
            {
                sb.AppendLine("                " + Identifier(Text(item, "value")) + ",");
            }
            sb.AppendLine("            };");
        }

        /// <summary>Какая сторона таблицы маппинга — значение справочника BCF, а какая — статус Navisworks.</summary>
        private enum MappingSide
        {
            Key,
            Value
        }

        private static void AppendMapping(StringBuilder sb, JObject root, string jsonKey, string name, string summary, MappingSide bcfSide)
        {
            var map = (JObject)root[jsonKey];

            sb.AppendLine("        /// <summary>" + summary + "</summary>");
            sb.AppendLine("        public static readonly IReadOnlyDictionary<string, string> " + name + " = new Dictionary<string, string>");
            sb.AppendLine("        {");
            foreach (JProperty property in map.Properties())
            {
                // Ключи вида $comment — документация внутри JSON, в код не идут
                if (property.Name.StartsWith("$", StringComparison.Ordinal)) continue;

                // Сторона BCF пишется константой, сторона Navisworks — строкой:
                // это значения ClashResultStatus, к справочнику отношения не имеющие.
                string key = bcfSide == MappingSide.Key
                    ? "TopicStatuses." + Identifier(property.Name)
                    : Literal(property.Name);
                string value = bcfSide == MappingSide.Value
                    ? "TopicStatuses." + Identifier((string)property.Value)
                    : Literal((string)property.Value);

                sb.AppendLine("            { " + key + ", " + value + " },");
            }
            sb.AppendLine("        };");
            sb.AppendLine();
        }

        private static List<JObject> Items(JObject root, string key)
        {
            var array = root[key] as JArray;
            if (array == null)
            {
                throw new InvalidOperationException("В справочнике нет раздела '" + key + "'.");
            }
            return array.OfType<JObject>().ToList();
        }

        private static string Text(JObject item, string key)
        {
            var token = item[key];
            return token == null ? null : (string)token;
        }

        private static bool Flag(JObject item, string key)
        {
            var token = item[key];
            return token != null && (bool)token;
        }

        private static string LabelRu(JObject item)
        {
            var labels = item["labels"] as JObject;
            if (labels == null) return null;
            return (string)labels["ru"];
        }

        /// <summary>
        /// Имя константы из wire-значения: убираем всё, кроме букв и цифр,
        /// каждое слово с заглавной. Регистр внутри слова сохраняем, иначе
        /// метки SITE (раздел ГП) и Site (выявлено на площадке) схлопнутся в одну.
        /// </summary>
        public static string Identifier(string value)
        {
            if (string.IsNullOrEmpty(value))
            {
                throw new ArgumentException("Пустое значение справочника не может стать именем константы.", nameof(value));
            }

            var sb = new StringBuilder();
            bool startOfWord = true;

            foreach (char c in value)
            {
                if (!char.IsLetterOrDigit(c))
                {
                    startOfWord = true;
                    continue;
                }

                sb.Append(startOfWord ? char.ToUpper(c, CultureInfo.InvariantCulture) : c);
                startOfWord = false;
            }

            if (sb.Length == 0 || char.IsDigit(sb[0]))
            {
                throw new InvalidOperationException("Значение '" + value + "' не даёт корректного имени константы C#.");
            }

            return sb.ToString();
        }

        private static string Literal(string value)
        {
            if (value == null) return "null";
            return "\"" + value.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
        }

        private static string Escape(string value)
        {
            return value == null ? null : value.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");
        }
    }
}
