// <auto-generated>
//     Сгенерировано из bcf-vocabularies/bcf-extensions.json (vocabularyVersion 1.0.0).
//
//     Руками не править. Обновление: dotnet run --project Bcf.Vocabulary.Generator
//     Расхождение этого файла со справочником роняет тест VocabularyDriftTests,
//     то есть ловится на сборке, а не в рантайме у пользователя.
// </auto-generated>

using System.Collections.Generic;

namespace Bcf.Core.Vocabulary
{
    public static partial class BcfVocabulary
    {
        /// <summary>Версия справочника (semver). Сервис отдаёт свою — расхождение мажорной части повод предупредить пользователя.</summary>
        public const string VocabularyVersion = "1.0.0";

        /// <summary>Основная целевая версия BCF.</summary>
        public const string TargetBcfVersion = "3.0";

        /// <summary>Переключаемая версия BCF для сторонних приёмников.</summary>
        public const string FallbackBcfVersion = "2.1";

        /// <summary>Тип замечания (TopicType).</summary>
        public static class TopicTypes
        {
            /// <summary>Коллизия</summary>
            public const string Clash = "Clash";
            /// <summary>Замечание</summary>
            public const string Issue = "Issue";
            /// <summary>Запрос изменения</summary>
            public const string Request = "Request";
            /// <summary>Вопрос</summary>
            public const string Question = "Question";
            /// <summary>Информация</summary>
            public const string Remark = "Remark";

            /// <summary>Значение по умолчанию при выгрузке.</summary>
            public const string Default = Clash;

            /// <summary>Все значения в порядке справочника.</summary>
            public static readonly IReadOnlyList<string> All = new[]
            {
                Clash,
                Issue,
                Request,
                Question,
                Remark,
            };

            /// <summary>Значения, доступные для выбора в UI: без помеченных deprecated. Старые данные с ними продолжают отображаться.</summary>
            public static readonly IReadOnlyList<string> Selectable = All;

            /// <summary>Русские подписи для UI. В файлы и в HTTP-тела не попадают никогда.</summary>
            public static readonly IReadOnlyDictionary<string, string> LabelsRu = new Dictionary<string, string>
            {
                { Clash, "Коллизия" },
                { Issue, "Замечание" },
                { Request, "Запрос изменения" },
                { Question, "Вопрос" },
                { Remark, "Информация" },
            };
        }

        /// <summary>Статус замечания (TopicStatus) и его жизненный цикл.</summary>
        public static class TopicStatuses
        {
            /// <summary>Новое</summary>
            public const string New = "New";
            /// <summary>Назначено</summary>
            public const string Assigned = "Assigned";
            /// <summary>В работе</summary>
            public const string InProgress = "In Progress";
            /// <summary>Устранено</summary>
            public const string Resolved = "Resolved";
            /// <summary>Переоткрыто</summary>
            public const string Reopened = "Reopened";
            /// <summary>Закрыто</summary>
            public const string Closed = "Closed";
            /// <summary>Отклонено</summary>
            public const string Rejected = "Rejected";
            /// <summary>Отложено</summary>
            public const string Deferred = "Deferred";

            /// <summary>Значение по умолчанию при выгрузке.</summary>
            public const string Default = New;

            /// <summary>Все значения в порядке справочника.</summary>
            public static readonly IReadOnlyList<string> All = new[]
            {
                New,
                Assigned,
                InProgress,
                Resolved,
                Reopened,
                Closed,
                Rejected,
                Deferred,
            };

            /// <summary>Значения, доступные для выбора в UI: без помеченных deprecated. Старые данные с ними продолжают отображаться.</summary>
            public static readonly IReadOnlyList<string> Selectable = All;

            /// <summary>Русские подписи для UI. В файлы и в HTTP-тела не попадают никогда.</summary>
            public static readonly IReadOnlyDictionary<string, string> LabelsRu = new Dictionary<string, string>
            {
                { New, "Новое" },
                { Assigned, "Назначено" },
                { InProgress, "В работе" },
                { Resolved, "Устранено" },
                { Reopened, "Переоткрыто" },
                { Closed, "Закрыто" },
                { Rejected, "Отклонено" },
                { Deferred, "Отложено" },
            };

            /// <summary>Конечные статусы: из них выходит только Reopened.</summary>
            public static readonly IReadOnlyList<string> Terminal = new[]
            {
                Closed,
                Rejected,
            };

            /// <summary>Статусы, которые нельзя ставить без комментария: закрытие без обоснования обесценивает систему.</summary>
            public static readonly IReadOnlyList<string> RequiresComment = new[]
            {
                Rejected,
                Deferred,
            };

            /// <summary>Статусы, требующие заполненного исполнителя.</summary>
            public static readonly IReadOnlyList<string> RequiresAssignee = new[]
            {
                Assigned,
                InProgress,
            };

            /// <summary>Разрешённые переходы. Авторитетная проверка — на сервере: сторонние клиенты об этих правилах не знают.</summary>
            public static readonly IReadOnlyDictionary<string, IReadOnlyList<string>> AllowedTransitions =
                new Dictionary<string, IReadOnlyList<string>>
            {
                { New, new[] { Assigned, Rejected, Deferred, Closed } },
                { Assigned, new[] { InProgress, Rejected, Deferred, New } },
                { InProgress, new[] { Resolved, Deferred, Assigned } },
                { Resolved, new[] { Closed, Reopened } },
                { Reopened, new[] { Assigned, InProgress, Rejected, Deferred } },
                { Closed, new[] { Reopened } },
                { Rejected, new[] { Reopened } },
                { Deferred, new[] { Assigned, InProgress, Rejected, Closed } },
            };
        }

        /// <summary>Приоритет замечания (Priority).</summary>
        public static class Priorities
        {
            /// <summary>Критичный</summary>
            public const string Critical = "Critical";
            /// <summary>Высокий</summary>
            public const string High = "High";
            /// <summary>Обычный</summary>
            public const string Normal = "Normal";
            /// <summary>Низкий</summary>
            public const string Low = "Low";

            /// <summary>Значение по умолчанию при выгрузке.</summary>
            public const string Default = Normal;

            /// <summary>Все значения в порядке справочника.</summary>
            public static readonly IReadOnlyList<string> All = new[]
            {
                Critical,
                High,
                Normal,
                Low,
            };

            /// <summary>Значения, доступные для выбора в UI: без помеченных deprecated. Старые данные с ними продолжают отображаться.</summary>
            public static readonly IReadOnlyList<string> Selectable = All;

            /// <summary>Русские подписи для UI. В файлы и в HTTP-тела не попадают никогда.</summary>
            public static readonly IReadOnlyDictionary<string, string> LabelsRu = new Dictionary<string, string>
            {
                { Critical, "Критичный" },
                { High, "Высокий" },
                { Normal, "Обычный" },
                { Low, "Низкий" },
            };
        }

        /// <summary>Метки замечания (TopicLabel): дисциплина, характер, источник.</summary>
        public static class TopicLabels
        {
            /// <summary>АР — архитектурные решения</summary>
            public const string ARC = "ARC";
            /// <summary>КР — конструктивные решения</summary>
            public const string STR = "STR";
            /// <summary>ОВ — отопление и вентиляция</summary>
            public const string HVAC = "HVAC";
            /// <summary>ВК — водоснабжение и канализация</summary>
            public const string PLUMB = "PLUMB";
            /// <summary>ЭОМ — электроснабжение</summary>
            public const string ELEC = "ELEC";
            /// <summary>ПТ — пожаротушение и ДУ</summary>
            public const string FIRE = "FIRE";
            /// <summary>СС — слаботочные системы</summary>
            public const string LV = "LV";
            /// <summary>ТХ — технологические решения</summary>
            public const string PROCESS = "PROCESS";
            /// <summary>ГП — генеральный план</summary>
            public const string SITE = "SITE";
            /// <summary>Жёсткая коллизия</summary>
            public const string HardClash = "Hard clash";
            /// <summary>Нарушение зазора</summary>
            public const string Clearance = "Clearance";
            /// <summary>Зона обслуживания</summary>
            public const string Maintenance = "Maintenance";
            /// <summary>Дубликат</summary>
            public const string Duplicate = "Duplicate";
            /// <summary>Ошибка моделирования</summary>
            public const string Modeling = "Modeling";
            /// <summary>Выявлено на площадке</summary>
            public const string Site = "Site";
            /// <summary>Автопроверка</summary>
            public const string Auto = "Auto";

            /// <summary>Все значения в порядке справочника.</summary>
            public static readonly IReadOnlyList<string> All = new[]
            {
                ARC,
                STR,
                HVAC,
                PLUMB,
                ELEC,
                FIRE,
                LV,
                PROCESS,
                SITE,
                HardClash,
                Clearance,
                Maintenance,
                Duplicate,
                Modeling,
                Site,
                Auto,
            };

            /// <summary>Значения, доступные для выбора в UI: без помеченных deprecated. Старые данные с ними продолжают отображаться.</summary>
            public static readonly IReadOnlyList<string> Selectable = All;

            /// <summary>Русские подписи для UI. В файлы и в HTTP-тела не попадают никогда.</summary>
            public static readonly IReadOnlyDictionary<string, string> LabelsRu = new Dictionary<string, string>
            {
                { ARC, "АР — архитектурные решения" },
                { STR, "КР — конструктивные решения" },
                { HVAC, "ОВ — отопление и вентиляция" },
                { PLUMB, "ВК — водоснабжение и канализация" },
                { ELEC, "ЭОМ — электроснабжение" },
                { FIRE, "ПТ — пожаротушение и ДУ" },
                { LV, "СС — слаботочные системы" },
                { PROCESS, "ТХ — технологические решения" },
                { SITE, "ГП — генеральный план" },
                { HardClash, "Жёсткая коллизия" },
                { Clearance, "Нарушение зазора" },
                { Maintenance, "Зона обслуживания" },
                { Duplicate, "Дубликат" },
                { Modeling, "Ошибка моделирования" },
                { Site, "Выявлено на площадке" },
                { Auto, "Автопроверка" },
            };

            /// <summary>Группа метки: discipline / nature / source. Нужна, чтобы в UI не мешать разделы проекта с характером коллизии.</summary>
            public static readonly IReadOnlyDictionary<string, string> Groups = new Dictionary<string, string>
            {
                { ARC, "discipline" },
                { STR, "discipline" },
                { HVAC, "discipline" },
                { PLUMB, "discipline" },
                { ELEC, "discipline" },
                { FIRE, "discipline" },
                { LV, "discipline" },
                { PROCESS, "discipline" },
                { SITE, "discipline" },
                { HardClash, "nature" },
                { Clearance, "nature" },
                { Maintenance, "nature" },
                { Duplicate, "nature" },
                { Modeling, "nature" },
                { Site, "source" },
                { Auto, "source" },
            };
        }

        /// <summary>Стадия проекта (Stage).</summary>
        public static class Stages
        {
            /// <summary>ЭП — эскизный проект</summary>
            public const string Concept = "Concept";
            /// <summary>П — проектная документация</summary>
            public const string Design = "Design";
            /// <summary>Р — рабочая документация</summary>
            public const string DetailedDesign = "Detailed Design";
            /// <summary>СМР — строительство</summary>
            public const string Construction = "Construction";
            /// <summary>ИД — исполнительная документация</summary>
            public const string AsBuilt = "As-built";

            /// <summary>Значение по умолчанию при выгрузке.</summary>
            public const string Default = Design;

            /// <summary>Все значения в порядке справочника.</summary>
            public static readonly IReadOnlyList<string> All = new[]
            {
                Concept,
                Design,
                DetailedDesign,
                Construction,
                AsBuilt,
            };

            /// <summary>Значения, доступные для выбора в UI: без помеченных deprecated. Старые данные с ними продолжают отображаться.</summary>
            public static readonly IReadOnlyList<string> Selectable = All;

            /// <summary>Русские подписи для UI. В файлы и в HTTP-тела не попадают никогда.</summary>
            public static readonly IReadOnlyDictionary<string, string> LabelsRu = new Dictionary<string, string>
            {
                { Concept, "ЭП — эскизный проект" },
                { Design, "П — проектная документация" },
                { DetailedDesign, "Р — рабочая документация" },
                { Construction, "СМР — строительство" },
                { AsBuilt, "ИД — исполнительная документация" },
            };
        }

        /// <summary>Статус Clash Detective -> TopicStatus BCF. Дефолты; пользователь переопределяет в диалоге экспорта.</summary>
        public static readonly IReadOnlyDictionary<string, string> NavisworksStatusToBcf = new Dictionary<string, string>
        {
            { "New", TopicStatuses.New },
            { "Active", TopicStatuses.Assigned },
            { "Reviewed", TopicStatuses.InProgress },
            { "Approved", TopicStatuses.Closed },
            { "Resolved", TopicStatuses.Resolved },
        };

        /// <summary>TopicStatus BCF -> статус Clash Detective. Отображение не биективно: набор статусов Navisworks беднее.</summary>
        public static readonly IReadOnlyDictionary<string, string> BcfStatusToNavisworks = new Dictionary<string, string>
        {
            { TopicStatuses.New, "New" },
            { TopicStatuses.Assigned, "Active" },
            { TopicStatuses.InProgress, "Active" },
            { TopicStatuses.Resolved, "Resolved" },
            { TopicStatuses.Reopened, "Active" },
            { TopicStatuses.Closed, "Approved" },
            { TopicStatuses.Rejected, "Approved" },
            { TopicStatuses.Deferred, "Reviewed" },
        };

    }
}
