// <auto-generated>
//     Generated from bcf-vocabularies/bcf-extensions.json (vocabularyVersion 1.0.0).
//
//     Do not edit by hand. To update: dotnet run --project Bcf.Vocabulary.Generator
//     A drift between this file and the vocabulary fails the VocabularyDriftTests test,
//     that is, it is caught at build time and not at run time on a user's machine.
// </auto-generated>

using System.Collections.Generic;

namespace Bcf.Core.Vocabulary
{
    public static partial class BcfVocabulary
    {
        /// <summary>
        /// The vocabulary version (semver). A service reports its own — a difference in the major part is reason to warn the user.
        /// Версия справочника (semver). Сервис отдаёт свою — расхождение мажорной части повод предупредить пользователя.
        /// </summary>
        public const string VocabularyVersion = "1.0.0";

        /// <summary>
        /// The primary target BCF version.
        /// Основная целевая версия BCF.
        /// </summary>
        public const string TargetBcfVersion = "3.0";

        /// <summary>
        /// The switchable BCF version for third-party receiving tools.
        /// Переключаемая версия BCF для сторонних приёмников.
        /// </summary>
        public const string FallbackBcfVersion = "2.1";

        /// <summary>
        /// The topic type (TopicType).
        /// Тип замечания (TopicType).
        /// </summary>
        public static class TopicTypes
        {
            /// <summary>
            /// Clash
            /// Коллизия
            /// </summary>
            public const string Clash = "Clash";
            /// <summary>
            /// Issue
            /// Замечание
            /// </summary>
            public const string Issue = "Issue";
            /// <summary>
            /// Request
            /// Запрос изменения
            /// </summary>
            public const string Request = "Request";
            /// <summary>
            /// Question
            /// Вопрос
            /// </summary>
            public const string Question = "Question";
            /// <summary>
            /// Remark
            /// Информация
            /// </summary>
            public const string Remark = "Remark";

            /// <summary>
            /// The value used by default when exporting.
            /// Значение по умолчанию при выгрузке.
            /// </summary>
            public const string Default = Clash;

            /// <summary>
            /// Every value, in the order of the vocabulary.
            /// Все значения в порядке справочника.
            /// </summary>
            public static readonly IReadOnlyList<string> All = new[]
            {
                Clash,
                Issue,
                Request,
                Question,
                Remark,
            };

            /// <summary>
            /// The values offered for choosing in an interface: without the ones marked deprecated. Old data carrying them is still displayed.
            /// Значения, доступные для выбора в интерфейсе: без помеченных deprecated. Старые данные с ними продолжают отображаться.
            /// </summary>
            public static readonly IReadOnlyList<string> Selectable = All;

            /// <summary>
            /// The Russian display labels for an interface. They never reach a file or an HTTP body.
            /// Русские подписи для интерфейса. В файлы и в тела HTTP не попадают никогда.
            /// </summary>
            public static readonly IReadOnlyDictionary<string, string> LabelsRu = new Dictionary<string, string>
            {
                { Clash, "Коллизия" },
                { Issue, "Замечание" },
                { Request, "Запрос изменения" },
                { Question, "Вопрос" },
                { Remark, "Информация" },
            };
        }

        /// <summary>
        /// The topic status (TopicStatus) and its lifecycle.
        /// Статус замечания (TopicStatus) и его жизненный цикл.
        /// </summary>
        public static class TopicStatuses
        {
            /// <summary>
            /// New
            /// Новое
            /// </summary>
            public const string New = "New";
            /// <summary>
            /// Assigned
            /// Назначено
            /// </summary>
            public const string Assigned = "Assigned";
            /// <summary>
            /// In Progress
            /// В работе
            /// </summary>
            public const string InProgress = "In Progress";
            /// <summary>
            /// Resolved
            /// Устранено
            /// </summary>
            public const string Resolved = "Resolved";
            /// <summary>
            /// Reopened
            /// Переоткрыто
            /// </summary>
            public const string Reopened = "Reopened";
            /// <summary>
            /// Closed
            /// Закрыто
            /// </summary>
            public const string Closed = "Closed";
            /// <summary>
            /// Rejected
            /// Отклонено
            /// </summary>
            public const string Rejected = "Rejected";
            /// <summary>
            /// Deferred
            /// Отложено
            /// </summary>
            public const string Deferred = "Deferred";

            /// <summary>
            /// The value used by default when exporting.
            /// Значение по умолчанию при выгрузке.
            /// </summary>
            public const string Default = New;

            /// <summary>
            /// Every value, in the order of the vocabulary.
            /// Все значения в порядке справочника.
            /// </summary>
            public static readonly IReadOnlyList<string> All = new[]
            {
                New,
                Assigned,
                InProgress,
                Resolved,
                Reopened,
                Closed,
                Rejected,
                Deferred,
            };

            /// <summary>
            /// The values offered for choosing in an interface: without the ones marked deprecated. Old data carrying them is still displayed.
            /// Значения, доступные для выбора в интерфейсе: без помеченных deprecated. Старые данные с ними продолжают отображаться.
            /// </summary>
            public static readonly IReadOnlyList<string> Selectable = All;

            /// <summary>
            /// The Russian display labels for an interface. They never reach a file or an HTTP body.
            /// Русские подписи для интерфейса. В файлы и в тела HTTP не попадают никогда.
            /// </summary>
            public static readonly IReadOnlyDictionary<string, string> LabelsRu = new Dictionary<string, string>
            {
                { New, "Новое" },
                { Assigned, "Назначено" },
                { InProgress, "В работе" },
                { Resolved, "Устранено" },
                { Reopened, "Переоткрыто" },
                { Closed, "Закрыто" },
                { Rejected, "Отклонено" },
                { Deferred, "Отложено" },
            };

            /// <summary>
            /// The terminal statuses: the only way out of them is Reopened.
            /// Конечные статусы: из них выходит только Reopened.
            /// </summary>
            public static readonly IReadOnlyList<string> Terminal = new[]
            {
                Closed,
                Rejected,
            };

            /// <summary>
            /// The statuses that must not be set without a comment: closing without a reason devalues the whole system.
            /// Статусы, которые нельзя ставить без комментария: закрытие без обоснования обесценивает всю систему.
            /// </summary>
            public static readonly IReadOnlyList<string> RequiresComment = new[]
            {
                Rejected,
                Deferred,
            };

            /// <summary>
            /// The statuses that need an assignee filled in.
            /// Статусы, требующие заполненного исполнителя.
            /// </summary>
            public static readonly IReadOnlyList<string> RequiresAssignee = new[]
            {
                Assigned,
                InProgress,
            };

            /// <summary>
            /// The allowed transitions. The authoritative check is on the server: third-party clients know nothing of these rules.
            /// Разрешённые переходы. Авторитетная проверка — на сервере: сторонние клиенты об этих правилах не знают.
            /// </summary>
            public static readonly IReadOnlyDictionary<string, IReadOnlyList<string>> AllowedTransitions =
                new Dictionary<string, IReadOnlyList<string>>
            {
                { New, new[] { Assigned, Rejected, Deferred, Closed } },
                { Assigned, new[] { InProgress, Rejected, Deferred, New } },
                { InProgress, new[] { Resolved, Deferred, Assigned } },
                { Resolved, new[] { Closed, Reopened } },
                { Reopened, new[] { Assigned, InProgress, Rejected, Deferred } },
                { Closed, new[] { Reopened } },
                { Rejected, new[] { Reopened } },
                { Deferred, new[] { Assigned, InProgress, Rejected, Closed } },
            };
        }

        /// <summary>
        /// The topic priority (Priority).
        /// Приоритет замечания (Priority).
        /// </summary>
        public static class Priorities
        {
            /// <summary>
            /// Critical
            /// Критичный
            /// </summary>
            public const string Critical = "Critical";
            /// <summary>
            /// High
            /// Высокий
            /// </summary>
            public const string High = "High";
            /// <summary>
            /// Normal
            /// Обычный
            /// </summary>
            public const string Normal = "Normal";
            /// <summary>
            /// Low
            /// Низкий
            /// </summary>
            public const string Low = "Low";

            /// <summary>
            /// The value used by default when exporting.
            /// Значение по умолчанию при выгрузке.
            /// </summary>
            public const string Default = Normal;

            /// <summary>
            /// Every value, in the order of the vocabulary.
            /// Все значения в порядке справочника.
            /// </summary>
            public static readonly IReadOnlyList<string> All = new[]
            {
                Critical,
                High,
                Normal,
                Low,
            };

            /// <summary>
            /// The values offered for choosing in an interface: without the ones marked deprecated. Old data carrying them is still displayed.
            /// Значения, доступные для выбора в интерфейсе: без помеченных deprecated. Старые данные с ними продолжают отображаться.
            /// </summary>
            public static readonly IReadOnlyList<string> Selectable = All;

            /// <summary>
            /// The Russian display labels for an interface. They never reach a file or an HTTP body.
            /// Русские подписи для интерфейса. В файлы и в тела HTTP не попадают никогда.
            /// </summary>
            public static readonly IReadOnlyDictionary<string, string> LabelsRu = new Dictionary<string, string>
            {
                { Critical, "Критичный" },
                { High, "Высокий" },
                { Normal, "Обычный" },
                { Low, "Низкий" },
            };
        }

        /// <summary>
        /// The topic labels (TopicLabel): discipline, nature, source.
        /// Метки замечания (TopicLabel): дисциплина, характер, источник.
        /// </summary>
        public static class TopicLabels
        {
            /// <summary>
            /// Architecture
            /// АР — архитектурные решения
            /// </summary>
            public const string ARC = "ARC";
            /// <summary>
            /// Structure
            /// КР — конструктивные решения
            /// </summary>
            public const string STR = "STR";
            /// <summary>
            /// HVAC
            /// ОВ — отопление и вентиляция
            /// </summary>
            public const string HVAC = "HVAC";
            /// <summary>
            /// Plumbing
            /// ВК — водоснабжение и канализация
            /// </summary>
            public const string PLUMB = "PLUMB";
            /// <summary>
            /// Electrical
            /// ЭОМ — электроснабжение
            /// </summary>
            public const string ELEC = "ELEC";
            /// <summary>
            /// Fire protection
            /// ПТ — пожаротушение и ДУ
            /// </summary>
            public const string FIRE = "FIRE";
            /// <summary>
            /// Low voltage
            /// СС — слаботочные системы
            /// </summary>
            public const string LV = "LV";
            /// <summary>
            /// Process
            /// ТХ — технологические решения
            /// </summary>
            public const string PROCESS = "PROCESS";
            /// <summary>
            /// Site
            /// ГП — генеральный план
            /// </summary>
            public const string SITE = "SITE";
            /// <summary>
            /// Hard clash
            /// Жёсткая коллизия
            /// </summary>
            public const string HardClash = "Hard clash";
            /// <summary>
            /// Clearance
            /// Нарушение зазора
            /// </summary>
            public const string Clearance = "Clearance";
            /// <summary>
            /// Maintenance access
            /// Зона обслуживания
            /// </summary>
            public const string Maintenance = "Maintenance";
            /// <summary>
            /// Duplicate
            /// Дубликат
            /// </summary>
            public const string Duplicate = "Duplicate";
            /// <summary>
            /// Modeling error
            /// Ошибка моделирования
            /// </summary>
            public const string Modeling = "Modeling";
            /// <summary>
            /// Found on site
            /// Выявлено на площадке
            /// </summary>
            public const string Site = "Site";
            /// <summary>
            /// Automated check
            /// Автопроверка
            /// </summary>
            public const string Auto = "Auto";

            /// <summary>
            /// Every value, in the order of the vocabulary.
            /// Все значения в порядке справочника.
            /// </summary>
            public static readonly IReadOnlyList<string> All = new[]
            {
                ARC,
                STR,
                HVAC,
                PLUMB,
                ELEC,
                FIRE,
                LV,
                PROCESS,
                SITE,
                HardClash,
                Clearance,
                Maintenance,
                Duplicate,
                Modeling,
                Site,
                Auto,
            };

            /// <summary>
            /// The values offered for choosing in an interface: without the ones marked deprecated. Old data carrying them is still displayed.
            /// Значения, доступные для выбора в интерфейсе: без помеченных deprecated. Старые данные с ними продолжают отображаться.
            /// </summary>
            public static readonly IReadOnlyList<string> Selectable = All;

            /// <summary>
            /// The Russian display labels for an interface. They never reach a file or an HTTP body.
            /// Русские подписи для интерфейса. В файлы и в тела HTTP не попадают никогда.
            /// </summary>
            public static readonly IReadOnlyDictionary<string, string> LabelsRu = new Dictionary<string, string>
            {
                { ARC, "АР — архитектурные решения" },
                { STR, "КР — конструктивные решения" },
                { HVAC, "ОВ — отопление и вентиляция" },
                { PLUMB, "ВК — водоснабжение и канализация" },
                { ELEC, "ЭОМ — электроснабжение" },
                { FIRE, "ПТ — пожаротушение и ДУ" },
                { LV, "СС — слаботочные системы" },
                { PROCESS, "ТХ — технологические решения" },
                { SITE, "ГП — генеральный план" },
                { HardClash, "Жёсткая коллизия" },
                { Clearance, "Нарушение зазора" },
                { Maintenance, "Зона обслуживания" },
                { Duplicate, "Дубликат" },
                { Modeling, "Ошибка моделирования" },
                { Site, "Выявлено на площадке" },
                { Auto, "Автопроверка" },
            };

            /// <summary>
            /// The group of a label: discipline / nature / source. It keeps an interface from mixing the sections of a project with the nature of a clash.
            /// Группа метки: discipline / nature / source. Нужна, чтобы в интерфейсе не мешать разделы проекта с характером коллизии.
            /// </summary>
            public static readonly IReadOnlyDictionary<string, string> Groups = new Dictionary<string, string>
            {
                { ARC, "discipline" },
                { STR, "discipline" },
                { HVAC, "discipline" },
                { PLUMB, "discipline" },
                { ELEC, "discipline" },
                { FIRE, "discipline" },
                { LV, "discipline" },
                { PROCESS, "discipline" },
                { SITE, "discipline" },
                { HardClash, "nature" },
                { Clearance, "nature" },
                { Maintenance, "nature" },
                { Duplicate, "nature" },
                { Modeling, "nature" },
                { Site, "source" },
                { Auto, "source" },
            };
        }

        /// <summary>
        /// The project stage (Stage).
        /// Стадия проекта (Stage).
        /// </summary>
        public static class Stages
        {
            /// <summary>
            /// Concept
            /// ЭП — эскизный проект
            /// </summary>
            public const string Concept = "Concept";
            /// <summary>
            /// Design
            /// П — проектная документация
            /// </summary>
            public const string Design = "Design";
            /// <summary>
            /// Detailed design
            /// Р — рабочая документация
            /// </summary>
            public const string DetailedDesign = "Detailed Design";
            /// <summary>
            /// Construction
            /// СМР — строительство
            /// </summary>
            public const string Construction = "Construction";
            /// <summary>
            /// As-built
            /// ИД — исполнительная документация
            /// </summary>
            public const string AsBuilt = "As-built";

            /// <summary>
            /// The value used by default when exporting.
            /// Значение по умолчанию при выгрузке.
            /// </summary>
            public const string Default = Design;

            /// <summary>
            /// Every value, in the order of the vocabulary.
            /// Все значения в порядке справочника.
            /// </summary>
            public static readonly IReadOnlyList<string> All = new[]
            {
                Concept,
                Design,
                DetailedDesign,
                Construction,
                AsBuilt,
            };

            /// <summary>
            /// The values offered for choosing in an interface: without the ones marked deprecated. Old data carrying them is still displayed.
            /// Значения, доступные для выбора в интерфейсе: без помеченных deprecated. Старые данные с ними продолжают отображаться.
            /// </summary>
            public static readonly IReadOnlyList<string> Selectable = All;

            /// <summary>
            /// The Russian display labels for an interface. They never reach a file or an HTTP body.
            /// Русские подписи для интерфейса. В файлы и в тела HTTP не попадают никогда.
            /// </summary>
            public static readonly IReadOnlyDictionary<string, string> LabelsRu = new Dictionary<string, string>
            {
                { Concept, "ЭП — эскизный проект" },
                { Design, "П — проектная документация" },
                { DetailedDesign, "Р — рабочая документация" },
                { Construction, "СМР — строительство" },
                { AsBuilt, "ИД — исполнительная документация" },
            };
        }

        /// <summary>
        /// A Clash Detective status to a BCF TopicStatus. Defaults; the user overrides them in the export settings.
        /// Статус Clash Detective → TopicStatus BCF. Умолчания; пользователь переопределяет их в настройках выгрузки.
        /// </summary>
        public static readonly IReadOnlyDictionary<string, string> NavisworksStatusToBcf = new Dictionary<string, string>
        {
            { "New", TopicStatuses.New },
            { "Active", TopicStatuses.Assigned },
            { "Reviewed", TopicStatuses.InProgress },
            { "Approved", TopicStatuses.Closed },
            { "Resolved", TopicStatuses.Resolved },
        };

        /// <summary>
        /// A BCF TopicStatus to a Clash Detective status. The mapping is not one to one: the Navisworks set of statuses is the poorer one.
        /// TopicStatus BCF → статус Clash Detective. Отображение не биективно: набор статусов Navisworks беднее.
        /// </summary>
        public static readonly IReadOnlyDictionary<string, string> BcfStatusToNavisworks = new Dictionary<string, string>
        {
            { TopicStatuses.New, "New" },
            { TopicStatuses.Assigned, "Active" },
            { TopicStatuses.InProgress, "Active" },
            { TopicStatuses.Resolved, "Resolved" },
            { TopicStatuses.Reopened, "Active" },
            { TopicStatuses.Closed, "Approved" },
            { TopicStatuses.Rejected, "Approved" },
            { TopicStatuses.Deferred, "Reviewed" },
        };

    }
}
